version: '3.8'

services:
  gateway:
    build: ./shareit-gateway
    image: mamaiwyd/shareit-gateway-image:latest
    container_name: shareit-gateway-container
    depends_on:
      - server
    environment:
      GATEWAY_PORT: 8080
      SHAREIT_SERVER_URL: http://server:9090
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16.1
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shareit
    volumes:
      - ./shareit-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./shareit-server
    image: mamaiwyd/shareit-server-image:latest
    container_name: shareit-server-container
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db-data:
